title: Coursera Test
email: vinayak.tiwari.ug20@gmail.com
description: >-
  This is my code repository for Coursera assignments.
baseurl: "/coursera-test/"
url: "https://vinayaktiwariug20.github.io"
github_username: vinayaktiwariug20

# Build settings
theme: minima
plugins:
  - jekyll-feed
