title: Coursera Test Repository
email: vinayak.tiwari.ug20@gmail.com
description: >-
  This is my code repository for Coursera assignments.
baseurl: "/coursera-test/"
url: "https://vinayaktiwariug20.github.io"
github_username: vinayaktiwariug20

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
